# Generated by Django 5.0.4 on 2024-05-27 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_provider_address'),
        ('app', '0002_vet_specialty'),
    ]

    operations = [
    ]
