# Generated by Django 5.0.4 on 2024-04-30 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_medi'),
        ('app', '0004_provider'),
    ]

    operations = [
    ]
